= Victoria Lim Yan Hui - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Ark
Ark is meant to be a desktop delivery management application built for our Software Engineering module CS2103 in the
National University of Singapore. This application's main target audience are delivery companies and small online store owners,
and aims to help them manage their deliveries.

The user interacts with the Ark application using a Command Line Interface, and it has a Graphic User Interface created with JavaFX.
It is written in Java language, and has about 14kLoC (Lines of Code).
You may access the Ark repository link:https://github.com/CS2103AUG2017-T16-B1/main[here].

Ark was built on top of link::https://github.com/nus-cs2103-AY1718S1/addressbook-level4[Addressbook - Level 4], an
addressbook application. A number of features were added and refactoring was done to develop the original codebase
into the parcel management application, Ark.

For a list of my more significant contributions You may click on the links below.
Functional code refers to the codes written to enhance the Ark application while Test code refers to the codes written
to automate testing for the Ark application.

*Code contributed*: [https://github.com/CS2103AUG2017-T16-B1/main/blob/master/collated/main/vicisapotato.md[Functional code]][https://github.com/CS2103AUG2017-T16-B1/main/blob/master/collated/test/vicisapotato.md[Test code]]

The following are my contributions to the project explained in detail:

=== Enhancement Added: Google Maps Browser

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=browser]

#End of Extract#

---

==== Justification

Since Ark is meant to assist in deliveries, it is necessary for Ark to have a Google Maps browser implemented
within the application to show to users the exact location of parcel delivery addresses.
This would enable our users to continue using Ark without the need to keep switching between our application
and a web browser, thus saving users time and hassle.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=browser]

#End of Extract#

---

=== Enhancement Added: Tab Command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tabCommand]

#End of Extract#

---

==== Justification

Since Ark has 4 different statuses for parcels, it is essential that our users are able to quickly
navigate between the different statuses. Hence we have implemented different parcelLists for undelivered and delivered
parcels. These lists are viewed in separate tabs in the parcelListPanel.
To improve usability for users of Ark to be able to quickly search between the different parcel statuses
without the need for a mouse, a `tab` command is required.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tabCommand]

#End of Extract#

---

=== Enhancement Added: Overdue Parcels Popup Window

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=overduePopup]

#End of Extract#

---

==== Justification

Since our application is meant to be used as a parcel manager, it is important that our users
know when they have overdue parcels. Since these parcels are either late for delivery or possibly
missing, it is important to notify the users of these overdue parcels. A popup window right at the
startup of the Ark application is the best way to notify users since it would be the first thing
users see whenever they startup Ark.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=overduePopup]

#End of Extract#

---

=== Enhancement Proposed:



=== Other contributions

* Changed the UI layout of MainWindow
(Pull requests https://github.com/CS2103AUG2017-T16-B1/main/pull/98[#98])

* Changed the UI layout of ParcelList and ParcelCard
(Pull requests https://github.com/CS2103AUG2017-T16-B1/main/pull/100[#100])
